// Brand artwork generated from the project's own SVG line icons:
//  - public/brand/moona-wheel.svg: the twelve signs in zodiac order (Aries … Pisces), counter-clockwise
//    from 9 o'clock like a chart, each exactly once (replaces the old raster logo whose wheel repeated
//    Libra/Scorpio/Capricorn and missed Aries/Sagittarius/Pisces).
//  - public/icons/*: app icons rendered from public/brand/moona-mark.svg with sharp (installed by Next.js).
// Usage: node scripts/make-brand.mjs   (re-run after the mark or the zodiac icons change; commit the output)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import sharp from "sharp";

const SIGNS = ["aries", "taurus", "gemini", "cancer", "leo", "virgo", "libra", "scorpio", "sagittarius", "capricorn", "aquarius", "pisces"];
const S = 480, C = S / 2;
const pathsOf = (sign) => [...readFileSync(`public/design/zodiac/${sign}.svg`, "utf8").matchAll(/\sd="([^"]+)"/g)].map((m) => m[1]);

const parts = [];
parts.push(`<circle cx="${C}" cy="${C}" r="232" stroke="#BFC5D2" stroke-opacity="0.55" stroke-width="1.5"/>`);
parts.push(`<circle cx="${C}" cy="${C}" r="176" stroke="#BFC5D2" stroke-opacity="0.35" stroke-width="1"/>`);
parts.push(`<circle cx="${C}" cy="${C}" r="120" stroke="#A394C7" stroke-opacity="0.45" stroke-width="1"/>`);
SIGNS.forEach((sign, i) => {
  // sign boundaries
  const b = Math.PI + (i * 30 * Math.PI) / 180;
  const [x1, y1, x2, y2] = [C + 176 * Math.cos(b), C - 176 * Math.sin(b), C + 232 * Math.cos(b), C - 232 * Math.sin(b)];
  parts.push(`<line x1="${x1.toFixed(1)}" y1="${y1.toFixed(1)}" x2="${x2.toFixed(1)}" y2="${y2.toFixed(1)}" stroke="#BFC5D2" stroke-opacity="0.35"/>`);
  // the sign's glyph at the middle of its 30° segment (Aries 0–30° starts at 9 o'clock, counter-clockwise)
  const a = Math.PI + ((i * 30 + 15) * Math.PI) / 180;
  const gx = C + 204 * Math.cos(a) - 18, gy = C - 204 * Math.sin(a) - 18;
  parts.push(`<g transform="translate(${gx.toFixed(1)} ${gy.toFixed(1)}) scale(0.75)" fill="none" stroke="#CDD2DC" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round">${pathsOf(sign).map((d) => `<path d="${d}"/>`).join("")}</g>`);
});
// centre: the crescent from the mark
parts.push(`<defs><mask id="w-cres"><rect width="${S}" height="${S}" fill="#fff"/><circle cx="${C + 22}" cy="${C - 18}" r="44" fill="#000"/></mask></defs>`);
parts.push(`<circle cx="${C - 6}" cy="${C + 4}" r="52" fill="#E4E7EE" mask="url(#w-cres)"/>`);

const wheel = `<svg xmlns="http://www.w3.org/2000/svg" width="${S}" height="${S}" viewBox="0 0 ${S} ${S}" fill="none">
  <!-- Generated by scripts/make-brand.mjs from public/design/zodiac. Twelve signs, each once, in order. -->
  ${parts.join("\n  ")}
</svg>
`;
writeFileSync("public/brand/moona-wheel.svg", wheel);
console.log("wrote public/brand/moona-wheel.svg");

const BG = { r: 14, g: 13, b: 22, alpha: 1 }; // --bg-0
mkdirSync("public/icons", { recursive: true });
const mark = readFileSync("public/brand/moona-mark.svg");
async function icon(size, scale, out) {
  const inner = Math.round(size * scale);
  const png = await sharp(mark, { density: 72 * (inner / 48) * 2 }).resize(inner, inner).png().toBuffer();
  await sharp({ create: { width: size, height: size, channels: 4, background: BG } }).composite([{ input: png, gravity: "centre" }]).png().toFile(out);
  console.log("wrote", out);
}
await icon(192, 0.8, "public/icons/icon-192.png");
await icon(512, 0.8, "public/icons/icon-512.png");
await icon(512, 0.62, "public/icons/maskable-512.png"); // inside the 80% safe circle
await icon(180, 0.78, "public/icons/apple-touch-icon.png");
await icon(48, 0.9, "public/icons/favicon-48.png");
