// Server keys (spec §3.2), each derived from SESSION_SECRET with HKDF so one leaked use can't forge
// another: visitor cookies, input hashes for the ledger, network buckets, operator cookies.
// SESSION_SECRET is generated by the team and set in the host's environment, never pasted into chat.
// - A deployment without it has no keys, and AI stays off.
// - `next dev` uses a fixed development secret, so a visitor cookie survives a restart.
// - Any production server (`next start`, even on a laptop at the venue) never uses that public
//   secret: without SESSION_SECRET it signs with a random key made at start-up, so nothing can be
//   forged and cookies simply end when the server restarts.
import "server-only";
import { hkdfSync, randomBytes } from "node:crypto";
import { isDeployed, type EnvLike } from "@/lib/host";

export interface Keys { cookie: Buffer; input: Buffer; net: Buffer; ops: Buffer }

const DEV_SECRET = "moona-local-development-only-secret-0000";
const PROCESS_SECRET = randomBytes(32).toString("base64url");
const cache = new Map<string, Keys>();
let warned = false;

/** The secret a server without SESSION_SECRET uses: the fixed one only under `next dev` and tests. */
export function fallbackSecret(env: EnvLike = process.env): string {
  return env.NODE_ENV === "production" ? PROCESS_SECRET : DEV_SECRET;
}

export function serverKeys(env: EnvLike = process.env): Keys | null {
  let secret = env.SESSION_SECRET ?? "";
  if (secret.length < 32) {
    if (isDeployed(env)) return null;
    if (!warned) {
      warned = true;
      console.warn("moona: SESSION_SECRET is not set; using a local key (never valid on a deployment)");
    }
    secret = fallbackSecret(env);
  }
  const hit = cache.get(secret);
  if (hit) return hit;
  const derive = (label: string) => Buffer.from(hkdfSync("sha256", secret, "moona-v1", label, 32));
  const keys = { cookie: derive("cookie"), input: derive("input"), net: derive("net"), ops: derive("ops") };
  cache.set(secret, keys);
  return keys;
}
