// Server keys (spec §3.2), each derived from SESSION_SECRET with HKDF so one leaked use can't forge
// another: visitor cookies, input hashes for the ledger, network buckets, operator cookies.
// SESSION_SECRET is generated by the team and set in the host's environment, never pasted into chat.
// A deployment without it has no keys, and AI stays off. Locally a fixed development secret is used,
// so a visitor cookie survives a dev-server restart; it is never valid on a deployment.
import "server-only";
import { hkdfSync } from "node:crypto";
import { isDeployed, type EnvLike } from "@/lib/host";

export interface Keys { cookie: Buffer; input: Buffer; net: Buffer; ops: Buffer }

const DEV_SECRET = "moona-local-development-only-secret-0000";
const cache = new Map<string, Keys>();
let warned = false;

export function serverKeys(env: EnvLike = process.env): Keys | null {
  let secret = env.SESSION_SECRET ?? "";
  if (secret.length < 32) {
    if (isDeployed(env)) return null;
    if (!warned) {
      warned = true;
      console.warn("moona: SESSION_SECRET is not set; using the local development key (never valid on a deployment)");
    }
    secret = DEV_SECRET;
  }
  const hit = cache.get(secret);
  if (hit) return hit;
  const derive = (label: string) => Buffer.from(hkdfSync("sha256", secret, "moona-v1", label, 32));
  const keys = { cookie: derive("cookie"), input: derive("input"), net: derive("net"), ops: derive("ops") };
  cache.set(secret, keys);
  return keys;
}
